export const userActionTypes = Object.freeze({
  REGISTER_USER: 'REGISTER_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER'
});

export const flowerActionTypes = Object.freeze({
  GET_FAVORITE_FLOWERS: 'GET_FAVORITE_FLOWERS',
  GET_FAVORITE_FLOWERS_SUCCESS: 'GET_FAVORITE_FLOWERS_SUCCESS',
  FAVORITE_FLOWER: 'FAVORITE_FLOWER',
  FAVORITE_FLOWER_SUCCESS: 'FAVORITE_FLOWER_SUCCESS',
  UNFAVORITE_FLOWER: 'UNFAVORITE_FLOWER',
  UNFAVORITE_FLOWER_SUCCESS: 'UNFAVORITE_FLOWER_SUCCESS'
});

export const uiActionTypes = Object.freeze({
  START_ACTION: 'START_ACTION',
  STOP_ACTION: 'STOP_ACTION',
  REFRESH_ACTION_START: 'REFRESH_ACTION_START',
  REFRESH_ACTION_STOP: 'REFRESH_ACTION_STOP',
  TOGGLE_POPUP_MESSAGE: 'TOGGLE_POPUP_MESSAGE'
});
