export const screenNames = Object.freeze({
  COMMENTS: 'COMMENTS',
  FLOWER_DETAILS: 'FLOWER_DETAILS',
  FLOWERS: 'FLOWERS',
  LATEST_SIGHTINGS: 'LATEST_SIGHTINGS',
  FAVORITES: 'FAVORITES',
  SETTINGS: 'SETTINGS',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  HOME: 'HOME',
  LOCATION: 'LOCATION',
  MAP: 'MAP',
  MENU: 'MENU'
});

export const stackNames = Object.freeze({
  COMMENTS_STACK: 'COMMENTS_STACK',
  HOME_STACK: 'HOME_STACK',
  LOCATION_STACK: 'LOCATION_STACK',
  MAP_STACK: 'MAP_STACK',
  MENU_STACK: 'MENU_STACK'
});
